# Generated by Django 5.1.6 on 2025-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('stock', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
